import type {
  Door,
  GameDefinition,
  GameEffect,
  ItemDef,
  ItemInstance,
  ItemUse,
  RoomDef,
} from "./types";
import { validateGame } from "./validate";

/**
 * The gameplay state of a running game. This is deliberately *serializable*
 * (plain data + arrays) so a playthrough can be snapshotted, persisted, and
 * resumed later — the foundation for "pick up where you left off" accounts,
 * leaderboards, and server-side saves.
 */
export interface GameState {
  currentRoomId: string;
  inventory: ItemInstance[];
  /** Items still lying in each room (room id → item instances). */
  roomItems: Map<string, ItemInstance[]>;
  /** Persistent flags/variables that doors and item effects can read/write. */
  flags: Record<string, boolean | string | number>;
  seenRooms: Set<string>;
  /** Narrative messages generated by the latest action. */
  lastMessages: string[];
  /** Points accumulated when `game.scoring.type === "points"`. */
  points: number;
  /** When set, the game has ended. */
  ended?: { message: string; outcome: "win" | "lose" };
}

/** A JSON-serializable snapshot of a session (for saves / resume). */
export interface SavedState {
  version: 1;
  currentRoomId: string;
  inventory: { id: string; charges: number; origin: string }[];
  roomItems: [string, { id: string; charges: number; origin: string }[]][];
  flags: Record<string, boolean | string | number>;
  seenRooms: string[];
  lastMessages: string[];
  points: number;
  ended?: { message: string; outcome: "win" | "lose" };
  startedAt: number;
  finishedAt?: number;
}

/** Result of an action, used by the UI. */
export interface ActionResult {
  ok: boolean;
  messages: string[];
  /** True if current room changed. */
  moved?: boolean;
  /** True if the game has ended. */
  ended?: { message: string; outcome: "win" | "lose" };
}

/** A change-listener subscription handle (returned by `engine.onChange`). */
export type Unsubscribe = () => void;

/**
 * The engine executes games. It is intentionally UI-agnostic: the renderer
 * drives it through the public methods and re-renders whenever `onChange`
 * fires. Engine also owns session timing + score, and can serialize itself.
 */
export class Engine {
  readonly game: GameDefinition;
  readonly roomsById: Map<string, RoomDef>;
  readonly itemsById: Map<string, ItemDef>;
  readonly state: GameState;

  /** Epoch ms the session started. Restored on `load`. */
  startedAt: number;
  /** Epoch ms the game finished (if it has ended). */
  finishedAt?: number;

  private listeners = new Set<() => void>();

  constructor(game: GameDefinition, saved?: SavedState) {
    // Fail loudly at construction time on structurally broken definitions
    // (bad door targets, duplicate ids, unknown unlock refs, ...).
    validateGame(game);

    this.game = game;
    this.roomsById = new Map(game.rooms.map((r) => [r.id, r]));
    this.itemsById = new Map();
    for (const room of game.rooms) {
      for (const item of room.items ?? []) this.itemsById.set(item.id, item);
    }
    if (!this.roomsById.has(game.startingRoom)) {
      throw new Error(`startingRoom "${game.startingRoom}" not found`);
    }

    if (saved) {
      // Resume from a snapshot instead of starting fresh.
      this.startedAt = saved.startedAt;
      this.finishedAt = saved.finishedAt;
      this.state = {
        currentRoomId: saved.currentRoomId,
        inventory: saved.inventory.map((i) => this.reviveInstance(i)),
        roomItems: new Map(
          saved.roomItems.map(([roomId, items]) => [
            roomId,
            items.map((i) => this.reviveInstance(i)),
          ]),
        ),
        flags: { ...saved.flags },
        seenRooms: new Set(saved.seenRooms),
        lastMessages: [...saved.lastMessages],
        points: saved.points ?? 0,
        ended: saved.ended,
      };
      return;
    }

    this.startedAt = Date.now();
    this.state = {
      currentRoomId: game.startingRoom,
      inventory: [],
      roomItems: new Map(),
      flags: {},
      seenRooms: new Set([game.startingRoom]),
      lastMessages: [],
      points: 0,
    };
    // Seed each room with its starting items (they stay in the room until the
    // player chooses to take them).
    for (const room of game.rooms) {
      const instances = (room.items ?? []).map((def) => this.makeInstance(def));
      this.state.roomItems.set(room.id, instances);
    }
  }

  /* --------------------------- change notification ------------------------ */

  /** Subscribe to state changes. Returns an unsubscribe function. */
  onChange(listener: () => void): Unsubscribe {
    this.listeners.add(listener);
    return () => this.listeners.delete(listener);
  }

  private emit(): void {
    for (const listener of this.listeners) listener();
  }

  /* ------------------------------- helpers ------------------------------- */

  private resetMessages(): void {
    this.state.lastMessages = [];
  }
  private tell(text: string): void {
    this.state.lastMessages.push(text);
  }

  private makeInstance(def: ItemDef, origin?: string): ItemInstance {
    return {
      def,
      id: def.id,
      charges: def.charges ?? 0,
      origin: origin ?? "",
    };
  }

  private reviveInstance(saved: {
    id: string;
    charges: number;
    origin: string;
  }): ItemInstance {
    const def = this.itemsById.get(saved.id);
    if (!def) throw new Error(`saved item "${saved.id}" not defined in game`);
    return { def, id: saved.id, charges: saved.charges, origin: saved.origin };
  }

  /* ------------------------------ navigation ----------------------------- */

  get currentRoom(): RoomDef {
    const r = this.roomsById.get(this.state.currentRoomId);
    if (!r) throw new Error("current room missing");
    return r;
  }

  /** Exits the player can actually traverse right now (unlocked). */
  get availableExits(): Door[] {
    return this.currentRoom.doors.filter((d) => this.isUnlocked(d));
  }

  /** Items currently lying in the current room (the player can take them). */
  get roomItemsHere(): ItemInstance[] {
    return this.state.roomItems.get(this.state.currentRoomId) ?? [];
  }

  isUnlocked(door: Door): boolean {
    if (!door.requiresFlag) return true;
    return this.state.flags[door.requiresFlag] === (door.requireValue ?? true);
  }

  tryMove(door: Door): ActionResult {
    this.resetMessages();
    if (this.state.ended) {
      this.tell("The story is over. Nothing left to do here.");
      this.emit();
      return { ok: false, messages: this.state.lastMessages };
    }
    if (!this.isUnlocked(door)) {
      this.tell(door.lockedText ?? "It's locked.");
      this.emit();
      return { ok: false, messages: this.state.lastMessages };
    }
    this.state.currentRoomId = door.to;
    this.state.seenRooms.add(door.to);
    const dest = this.currentRoom;
    this.tell(dest.description || `You enter ${dest.name || "a room"}.`);
    this.emit();
    return {
      ok: true,
      moved: true,
      messages: this.state.lastMessages,
    };
  }

  /* --------------------------------- items -------------------------------- */

  /** Pick up an item lying in the current room, moving it into the inventory. */
  takeItem(item: ItemInstance): ActionResult {
    this.resetMessages();
    if (this.state.ended) {
      this.tell("The story is over. No point carrying extra now.");
      this.emit();
      return { ok: false, messages: this.state.lastMessages };
    }
    const roomItems = this.state.roomItems.get(this.state.currentRoomId) ?? [];
    const idx = roomItems.indexOf(item);
    if (idx === -1) {
      this.tell("That item isn't here.");
      this.emit();
      return { ok: false, messages: this.state.lastMessages };
    }
    roomItems.splice(idx, 1);
    this.state.roomItems.set(this.state.currentRoomId, roomItems);
    this.state.inventory.push(item);
    this.tell(`You take ${item.def.name}.`);
    this.emit();
    return { ok: true, messages: this.state.lastMessages };
  }

  useItem(instance: ItemInstance, use: ItemUse): ActionResult {
    this.resetMessages();
    if (this.state.ended) {
      this.tell("The story is over. Your last actions have already been spent.");
      this.emit();
      return { ok: false, messages: this.state.lastMessages };
    }
    if (instance.def.uses.indexOf(use) === -1) {
      this.tell("You can't do that.");
      this.emit();
      return { ok: false, messages: this.state.lastMessages };
    }
    if (!this.useAvailable(use, instance)) {
      this.tell("You can't do that right now.");
      this.emit();
      return { ok: false, messages: this.state.lastMessages };
    }
    this.applyEffects(use.effects);

    if (use.chargesPerUse) instance.charges -= use.chargesPerUse;
    const isChargeItem = instance.def.charges !== undefined;
    const emptiedRemovable =
      isChargeItem && instance.charges <= 0 && instance.def.removableWhenEmpty !== false;
    if (use.consumes || emptiedRemovable) {
      const i = this.state.inventory.indexOf(instance);
      if (i !== -1) {
        this.state.inventory.splice(i, 1);
        this.tell(`The ${instance.def.name} is used up and gone.`);
      }
    }

    if (this.state.ended && this.finishedAt === undefined) {
      this.finishedAt = Date.now();
    }
    this.emit();
    return {
      ok: this.state.lastMessages.length > 0,
      messages: this.state.lastMessages,
      ended: this.state.ended,
    };
  }

  /* -------------------------------- effects ------------------------------- */

  private applyEffects(effects: GameEffect[]): void {
    const context = new EffectContext(this, this.state.lastMessages);
    for (const effect of effects) context.apply(effect);
  }

  /** Set a game flag. (Used by effects; callers should emit after mutating.) */
  setFlag(flag: string, value: boolean | string | number): void {
    this.state.flags[flag] = value;
  }

  /**
   * Whether a given item-use is currently offered to the player. Pass the
   * owning `instance` to also gate on its charges: a charged item at 0 is
   * treated as empty for uses that would drain it.
   */
  useAvailable(use: ItemUse, instance?: ItemInstance): boolean {
    if (use.requiresFlag) {
      if (this.state.flags[use.requiresFlag] !== (use.requireValue ?? true)) {
        return false;
      }
    }
    // A charge-limited item that is out of fuel can't be used for charged
    // actions (though the item itself may persist via removableWhenEmpty).
    if (instance && instance.def.charges !== undefined && instance.charges <= 0) {
      if ((use.chargesPerUse ?? 0) > 0) return false;
    }
    return true;
  }

  /** The uses of an item that are currently available. */
  availableUses(instance: ItemInstance): ItemUse[] {
    return instance.def.uses.filter((u) => this.useAvailable(u, instance));
  }

  /* -------------------------- scoring & persistence ----------------------- */

  /** Whether the game awards a score at all. */
  get isScored(): boolean {
    return this.game.scoring !== undefined;
  }

  /**
   * The score: for "points" games it's the accumulated points; for "time"
   * games it's the elapsed milliseconds (lower is better). Undefined when the
   * game is not scored.
   */
  get score(): number | undefined {
    const s = this.game.scoring;
    if (!s) return undefined;
    if (s.type === "points") return this.state.points;
    return this.finishedAt !== undefined
      ? this.finishedAt - this.startedAt
      : Date.now() - this.startedAt;
  }

  /** Elapsed play time in ms (frozen once the game ends). */
  get elapsedMs(): number {
    if (this.finishedAt !== undefined) return this.finishedAt - this.startedAt;
    return Date.now() - this.startedAt;
  }

  /** A JSON-serializable snapshot that can be persisted and fed back to `load`. */
  serialize(): SavedState {
    const inst = (i: ItemInstance) => ({
      id: i.id,
      charges: i.charges,
      origin: i.origin,
    });
    return {
      version: 1,
      currentRoomId: this.state.currentRoomId,
      inventory: this.state.inventory.map(inst),
      roomItems: [...this.state.roomItems.entries()].map(([roomId, items]) => [
        roomId,
        items.map(inst),
      ]),
      flags: { ...this.state.flags },
      seenRooms: [...this.state.seenRooms],
      lastMessages: [...this.state.lastMessages],
      points: this.state.points,
      ended: this.state.ended,
      startedAt: this.startedAt,
      finishedAt: this.finishedAt,
    };
  }

  /** Build a new Engine resumed from a saved snapshot of the same game. */
  static load(game: GameDefinition, saved: SavedState): Engine {
    const engine = new Engine(game, saved);
    engine.emit();
    return engine;
  }

  /* ---------------------------------- map ---------------------------------- */

  /**
   * Compute a map of rooms using explicit coordinates where provided and
   * filling the rest from door traversal (simple auto-tiling).
   */
  computeMap(): { room: RoomDef; x: number; y: number }[] {
    const coords = new Map<string, { x: number; y: number }>();
    for (const room of this.game.rooms) {
      if (room.map) coords.set(room.id, { x: room.map.x, y: room.map.y });
    }
    // DFS auto-layout for any room missing coordinates.
    const visit = (id: string, x: number, y: number, from?: string): void => {
      if (coords.has(id) && from !== undefined) return;
      if (!coords.has(id)) coords.set(id, { x, y });
      const room = this.roomsById.get(id)!;
      for (const door of room.doors) {
        if (door.to === from) continue;
        const [nx, ny] = headingOffset(door.direction);
        if (!coords.has(door.to)) visit(door.to, x + nx, y + ny, id);
      }
    };
    if (!coords.has(this.game.startingRoom)) {
      visit(this.game.startingRoom, 0, 0);
    }
    // Also visit explicitly-placed rooms to hang their neighbours.
    for (const room of this.game.rooms) {
      if (room.map) visit(room.id, room.map.x, room.map.y);
    }
    return this.game.rooms.map((room) => ({
      room,
      x: coords.get(room.id)?.x ?? 0,
      y: coords.get(room.id)?.y ?? 0,
    }));
  }
}

function headingOffset(direction: string): [number, number] {
  const d = direction.toLowerCase();
  if (d.includes("north")) return [0, -1];
  if (d.includes("east")) return [1, 0];
  if (d.includes("south")) return [0, 1];
  if (d.includes("west")) return [-1, 0];
  return [0, 0];
}

/** Applies effects, allowing them to query the live engine state. */
class EffectContext {
  constructor(
    private engine: Engine,
    private messages: string[],
  ) {}

  apply(effect: GameEffect): void {
    switch (effect.type) {
      case "message":
        this.messages.push(effect.text);
        break;
      case "destroyItem":
        this.destroyFromInventory(effect.itemId);
        break;
      case "setItemCharges": {
        const inst = this.findItem(effect.itemId);
        if (inst) inst.charges = effect.charges;
        break;
      }
      case "setFlag":
        this.engine.setFlag(effect.flag, effect.value);
        break;
      case "addPoints":
        this.engine.state.points += effect.amount;
        break;
      case "unlockExit": {
        const room = this.engine.roomsById.get(effect.roomId);
        const door = room?.doors.find((d) => d.direction === effect.direction);
        if (!room || !door) {
          this.messages.push("That exit doesn't seem to exist.");
          break;
        }
        if (!door.requiresFlag) {
          this.messages.push("That exit is already open.");
          break;
        }
        this.engine.setFlag(door.requiresFlag, true);
        if (effect.message) this.messages.push(effect.message);
        break;
      }
      case "endGame": {
        this.engine.state.ended = {
          message: effect.message,
          outcome: effect.outcome,
        };
        this.engine.state.points += effect.points ?? 0;
        this.messages.push(effect.message);
        break;
      }
    }
  }

  private findItem(id: string): ItemInstance | undefined {
    return this.engine.state.inventory.find((i) => i.id === id);
  }
  private destroyFromInventory(id: string): void {
    const inst = this.engine.state.inventory.find((i) => i.id === id);
    if (inst) {
      const i = this.engine.state.inventory.indexOf(inst);
      if (i !== -1) this.engine.state.inventory.splice(i, 1);
    }
  }
}